#!/bin/sh

uci -q batch <<'EOF'
set gpsd.core=gpsd
set gpsd.core.enabled='1'
set gpsd.core.readonly='1'
delete gpsd.core.devices
add_list gpsd.core.devices='/dev/ttyAMA0'
set gpsd.core.listen_globally='0'
set gpsd.core.port='2947'

set osi-gateway-gps.core=core
set osi-gateway-gps.core.enabled='1'
set osi-gateway-gps.core.gpsd_host='127.0.0.1'
set osi-gateway-gps.core.gpsd_port='2947'
set osi-gateway-gps.core.poll_interval_s='60'
set osi-gateway-gps.core.stale_after_s='900'
set osi-gateway-gps.core.min_move_m='20'
set osi-gateway-gps.core.native_probe_enabled='1'
set osi-gateway-gps.core.chirpstack_mirror_enabled='1'
set osi-gateway-gps.core.chirpstack_mirror_threshold_m='20'
set osi-gateway-gps.core.serial_device='/dev/ttyAMA0'
set osi-gateway-gps.core.serial_baud='9600'
commit gpsd
commit osi-gateway-gps
EOF

/etc/init.d/gpsd enable
/etc/init.d/osi-gateway-gps enable

exit 0
