-- risk: data
-- GENERATED by scripts/generate-journal-catalog.js; do not edit by hand.
-- Source: SoilManageR management-data template v2.6 + scripts/journal-catalog-core.js.
-- catalog-row-content-sha256: 982823099f7674bed55d8f322aaecd6dd295b9cb82c3f676647546ae20205d5f

-- journal_templates
INSERT INTO journal_templates(code,version,labels_json,definition_json,active)
SELECT 'farmer_quick',2,'{"en":"Quick"}','{"sections":[{"code":"what_where_when","fields":["activity_code","plot_uuid","occurred_start"]},{"code":"key_values","fields":["attr.irrigation_depth","attr.amount_mass_area_product","attr.amount_volume_area_product","note"]},{"code":"carried_forward_details","fields":["attr.operator","attr.equipment","attr.method"]}],"max_primary_fields":5,"carry_forward":["attr.operator","attr.equipment","attr.method"]}',1
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 2
  AND NOT EXISTS (SELECT 1 FROM journal_templates WHERE code='farmer_quick' AND version=2);

-- Immutable v2 postconditions. Each mismatch deliberately attempts id=0,
-- tripping journal_catalog_state CHECK(id=1) before state can be stamped.
INSERT INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at)
SELECT 0,0,'catalog-v2-postcondition-failed','2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 2
  AND NOT EXISTS (SELECT 1 FROM journal_templates WHERE code='farmer_quick' AND version=2 AND labels_json='{"en":"Quick"}' AND definition_json='{"sections":[{"code":"what_where_when","fields":["activity_code","plot_uuid","occurred_start"]},{"code":"key_values","fields":["attr.irrigation_depth","attr.amount_mass_area_product","attr.amount_volume_area_product","note"]},{"code":"carried_forward_details","fields":["attr.operator","attr.equipment","attr.method"]}],"max_primary_fields":5,"carry_forward":["attr.operator","attr.equipment","attr.method"]}' AND active=1);

-- journal_catalog_state
INSERT OR IGNORE INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at) VALUES (1,2,'051fa32594776e7f578192be292415211e5a9809d0cb10160c312906ca63a669','2026-07-12T00:00:00.000Z');
UPDATE journal_catalog_state SET catalog_version=2,catalog_hash='051fa32594776e7f578192be292415211e5a9809d0cb10160c312906ca63a669',updated_at='2026-07-12T00:00:00.000Z' WHERE id=1 AND catalog_version <= 2;
