-- risk: data
-- GENERATED by scripts/generate-journal-catalog.js; do not edit by hand.
-- Source: SoilManageR management-data template v2.6 + scripts/journal-catalog-core.js.
-- catalog-row-content-sha256: ad7e38274d5b63aa6e6fb0ded9eabb127c2126f1226e251d8955af14c999fe01

-- journal_vocab
INSERT INTO journal_vocab(code,kind,parent_code,value_type,quantity_kind,basis,default_unit_code,labels_json,icon_key,constraints_json,scope,active,sort_order,sync_version,created_at)
SELECT 'attr.variety','attribute',NULL,'text',NULL,NULL,NULL,'{"en":"Variety"}',NULL,'{"maxlength":120,"autocomplete":"variety_by_crop"}','core',1,160,0,'2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='attr.variety');
INSERT INTO journal_vocab(code,kind,parent_code,value_type,quantity_kind,basis,default_unit_code,labels_json,icon_key,constraints_json,scope,active,sort_order,sync_version,created_at)
SELECT 'choice.crop.permanent_grassland','choice','attr.crop',NULL,NULL,NULL,NULL,'{"en":"Permanent grassland"}',NULL,NULL,'core',1,4000,0,'2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.permanent_grassland');
INSERT INTO journal_vocab(code,kind,parent_code,value_type,quantity_kind,basis,default_unit_code,labels_json,icon_key,constraints_json,scope,active,sort_order,sync_version,created_at)
SELECT 'choice.crop.field_vegetable','choice','attr.crop',NULL,NULL,NULL,NULL,'{"en":"Field vegetable"}',NULL,NULL,'core',1,4010,0,'2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.field_vegetable');
INSERT INTO journal_vocab(code,kind,parent_code,value_type,quantity_kind,basis,default_unit_code,labels_json,icon_key,constraints_json,scope,active,sort_order,sync_version,created_at)
SELECT 'choice.crop.green_manure_cover','choice','attr.crop',NULL,NULL,NULL,NULL,'{"en":"Green manure / cover crop"}',NULL,NULL,'core',1,4020,0,'2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.green_manure_cover');
INSERT INTO journal_vocab(code,kind,parent_code,value_type,quantity_kind,basis,default_unit_code,labels_json,icon_key,constraints_json,scope,active,sort_order,sync_version,created_at)
SELECT 'choice.crop.fallow','choice','attr.crop',NULL,NULL,NULL,NULL,'{"en":"Fallow"}',NULL,NULL,'core',1,4030,0,'2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.fallow');
INSERT INTO journal_vocab(code,kind,parent_code,value_type,quantity_kind,basis,default_unit_code,labels_json,icon_key,constraints_json,scope,active,sort_order,sync_version,created_at)
SELECT 'choice.crop.other','choice','attr.crop',NULL,NULL,NULL,NULL,'{"en":"Other"}',NULL,NULL,'core',1,4040,0,'2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.other');

-- Immutable v4 postconditions. Each mismatch deliberately attempts id=0,
-- tripping journal_catalog_state CHECK(id=1) before state can be stamped.
INSERT INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at)
SELECT 0,0,'catalog-v4-postcondition-failed','2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='attr.variety' AND kind='attribute' AND parent_code IS NULL AND value_type='text' AND quantity_kind IS NULL AND basis IS NULL AND default_unit_code IS NULL AND labels_json='{"en":"Variety"}' AND icon_key IS NULL AND constraints_json='{"maxlength":120,"autocomplete":"variety_by_crop"}' AND scope='core' AND active=1 AND sort_order=160 AND sync_version=0 AND created_at='2026-07-12T00:00:00.000Z');
INSERT INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at)
SELECT 0,0,'catalog-v4-postcondition-failed','2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.permanent_grassland' AND kind='choice' AND parent_code='attr.crop' AND value_type IS NULL AND quantity_kind IS NULL AND basis IS NULL AND default_unit_code IS NULL AND labels_json='{"en":"Permanent grassland"}' AND icon_key IS NULL AND constraints_json IS NULL AND scope='core' AND active=1 AND sort_order=4000 AND sync_version=0 AND created_at='2026-07-12T00:00:00.000Z');
INSERT INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at)
SELECT 0,0,'catalog-v4-postcondition-failed','2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.field_vegetable' AND kind='choice' AND parent_code='attr.crop' AND value_type IS NULL AND quantity_kind IS NULL AND basis IS NULL AND default_unit_code IS NULL AND labels_json='{"en":"Field vegetable"}' AND icon_key IS NULL AND constraints_json IS NULL AND scope='core' AND active=1 AND sort_order=4010 AND sync_version=0 AND created_at='2026-07-12T00:00:00.000Z');
INSERT INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at)
SELECT 0,0,'catalog-v4-postcondition-failed','2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.green_manure_cover' AND kind='choice' AND parent_code='attr.crop' AND value_type IS NULL AND quantity_kind IS NULL AND basis IS NULL AND default_unit_code IS NULL AND labels_json='{"en":"Green manure / cover crop"}' AND icon_key IS NULL AND constraints_json IS NULL AND scope='core' AND active=1 AND sort_order=4020 AND sync_version=0 AND created_at='2026-07-12T00:00:00.000Z');
INSERT INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at)
SELECT 0,0,'catalog-v4-postcondition-failed','2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.fallow' AND kind='choice' AND parent_code='attr.crop' AND value_type IS NULL AND quantity_kind IS NULL AND basis IS NULL AND default_unit_code IS NULL AND labels_json='{"en":"Fallow"}' AND icon_key IS NULL AND constraints_json IS NULL AND scope='core' AND active=1 AND sort_order=4030 AND sync_version=0 AND created_at='2026-07-12T00:00:00.000Z');
INSERT INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at)
SELECT 0,0,'catalog-v4-postcondition-failed','2026-07-12T00:00:00.000Z'
WHERE COALESCE((SELECT catalog_version FROM journal_catalog_state WHERE id=1),0) <= 4
  AND NOT EXISTS (SELECT 1 FROM journal_vocab WHERE code='choice.crop.other' AND kind='choice' AND parent_code='attr.crop' AND value_type IS NULL AND quantity_kind IS NULL AND basis IS NULL AND default_unit_code IS NULL AND labels_json='{"en":"Other"}' AND icon_key IS NULL AND constraints_json IS NULL AND scope='core' AND active=1 AND sort_order=4040 AND sync_version=0 AND created_at='2026-07-12T00:00:00.000Z');

-- journal_catalog_state
INSERT OR IGNORE INTO journal_catalog_state(id,catalog_version,catalog_hash,updated_at) VALUES (1,4,'3f981d26dee98ee5439fac57894309658f027d2ba525ae0af972c6fc647a64af','2026-07-12T00:00:00.000Z');
UPDATE journal_catalog_state SET catalog_version=4,catalog_hash='3f981d26dee98ee5439fac57894309658f027d2ba525ae0af972c6fc647a64af',updated_at='2026-07-12T00:00:00.000Z' WHERE id=1 AND catalog_version <= 4;
