-- risk: additive
-- 0067: the daily agronomy record replicates to the cloud (spec
-- docs/superpowers/specs/2026-09-27-daily-agronomy-parity-design.md, B3). A row is
-- inserted at sync_version 1 and every real change adds 1; a row is never deleted,
-- only retracted by an update (null values, null_reason 'retracted'), so its
-- version never goes back. Both triggers are migration-owned: sync-init-fn does
-- not create them. A zone without a UUID emits nothing (zone guard in WHEN).
ALTER TABLE zone_daily_agronomy ADD COLUMN sync_version INTEGER NOT NULL DEFAULT 0;

DROP TRIGGER IF EXISTS trg_dp_zone_agronomy_outbox_ai;
CREATE TRIGGER trg_dp_zone_agronomy_outbox_ai AFTER INSERT ON zone_daily_agronomy FOR EACH ROW WHEN EXISTS ( SELECT 1 FROM sync_link_state WHERE peer_node = 'cloud' AND linked = 1 ) AND EXISTS ( SELECT 1 FROM irrigation_zones WHERE id = NEW.zone_id AND deleted_at IS NULL AND zone_uuid IS NOT NULL ) BEGIN INSERT INTO sync_outbox(event_uuid, aggregate_type, aggregate_key, op, payload_json, sync_version, occurred_at, gateway_device_eui) VALUES (lower(hex(randomblob(16))), 'ZONE_AGRONOMY', (SELECT zone_uuid FROM irrigation_zones WHERE id = NEW.zone_id) || '|' || NEW.date, 'ZONE_AGRONOMY_UPSERTED', json_object('contract_version', 1, 'zone_id', NEW.zone_id, 'zone_uuid', (SELECT zone_uuid FROM irrigation_zones WHERE id = NEW.zone_id), 'date', NEW.date, 'et0_mm', NEW.et0_mm, 'et0_tier', NEW.et0_tier, 'et0_source', NEW.et0_source, 'et0_station_id', NEW.et0_station_id, 'location_key', NEW.location_key, 'kc', NEW.kc, 'kc_source', NEW.kc_source, 'kc_stage_day', NEW.kc_stage_day, 'stage_overrun', NEW.stage_overrun, 'crop_type', NEW.crop_type, 'phenological_stage', NEW.phenological_stage, 'stage_started_on', NEW.stage_started_on, 'etc_mm', NEW.etc_mm, 'hours_present', NEW.hours_present, 'expected_hours', NEW.expected_hours, 'null_reason', NEW.null_reason, 'computed_at', NEW.computed_at, 'gateway_device_eui', COALESCE((SELECT gateway_device_eui FROM irrigation_zones WHERE id = NEW.zone_id), NULLIF(trim((SELECT gateway_device_eui FROM sync_link_state WHERE peer_node='cloud')),'')), 'sync_version', NEW.sync_version ), NEW.sync_version, strftime('%Y-%m-%dT%H:%M:%fZ','now'), COALESCE((SELECT gateway_device_eui FROM irrigation_zones WHERE id = NEW.zone_id), NULLIF(trim((SELECT gateway_device_eui FROM sync_link_state WHERE peer_node='cloud')),''))); END;

DROP TRIGGER IF EXISTS trg_dp_zone_agronomy_outbox_au;
CREATE TRIGGER trg_dp_zone_agronomy_outbox_au AFTER UPDATE ON zone_daily_agronomy FOR EACH ROW WHEN EXISTS ( SELECT 1 FROM sync_link_state WHERE peer_node = 'cloud' AND linked = 1 ) AND EXISTS ( SELECT 1 FROM irrigation_zones WHERE id = NEW.zone_id AND deleted_at IS NULL AND zone_uuid IS NOT NULL ) AND COALESCE(NEW.sync_version,0) <> COALESCE(OLD.sync_version,0) BEGIN INSERT INTO sync_outbox(event_uuid, aggregate_type, aggregate_key, op, payload_json, sync_version, occurred_at, gateway_device_eui) VALUES (lower(hex(randomblob(16))), 'ZONE_AGRONOMY', (SELECT zone_uuid FROM irrigation_zones WHERE id = NEW.zone_id) || '|' || NEW.date, 'ZONE_AGRONOMY_UPSERTED', json_object('contract_version', 1, 'zone_id', NEW.zone_id, 'zone_uuid', (SELECT zone_uuid FROM irrigation_zones WHERE id = NEW.zone_id), 'date', NEW.date, 'et0_mm', NEW.et0_mm, 'et0_tier', NEW.et0_tier, 'et0_source', NEW.et0_source, 'et0_station_id', NEW.et0_station_id, 'location_key', NEW.location_key, 'kc', NEW.kc, 'kc_source', NEW.kc_source, 'kc_stage_day', NEW.kc_stage_day, 'stage_overrun', NEW.stage_overrun, 'crop_type', NEW.crop_type, 'phenological_stage', NEW.phenological_stage, 'stage_started_on', NEW.stage_started_on, 'etc_mm', NEW.etc_mm, 'hours_present', NEW.hours_present, 'expected_hours', NEW.expected_hours, 'null_reason', NEW.null_reason, 'computed_at', NEW.computed_at, 'gateway_device_eui', COALESCE((SELECT gateway_device_eui FROM irrigation_zones WHERE id = NEW.zone_id), NULLIF(trim((SELECT gateway_device_eui FROM sync_link_state WHERE peer_node='cloud')),'')), 'sync_version', NEW.sync_version ), NEW.sync_version, strftime('%Y-%m-%dT%H:%M:%fZ','now'), COALESCE((SELECT gateway_device_eui FROM irrigation_zones WHERE id = NEW.zone_id), NULLIF(trim((SELECT gateway_device_eui FROM sync_link_state WHERE peer_node='cloud')),''))); END;
