-- Uganda schema-reconciliation table-rebuild artifact (2026-09-11)
-- GENERATED by scripts/ops/generate-uganda-schema-rebuild-20260911.js - do not hand-edit.
-- Source: database/migrations/ordered/0001__baseline.sql (reference(1)), verbatim DDL bodies.
-- Design: docs/superpowers/specs/2026-09-11-uganda-schema-reconciliation-design.md
-- Fixes the 17 residual diffs left after the additive catch-up artifact
-- (scripts/ops/uganda-catchup-20260911.sql) + repair-sync-outbox-v2.js, all on
-- 6 tables that already exist (table-rebuild class, sqlite.org/lang_altertable.html §7).
--
-- DO NOT pipe this file directly to `sqlite3` on a live device. It is a
-- reviewable RENDERING of the DDL each table block runs; the sanctioned
-- execution path is `generate-uganda-schema-rebuild-20260911.js --apply <db>`,
-- which: (1) preflights the exact 17-diff drift signature this artifact was
-- designed against and refuses on any mismatch; (2) runs per-table, skipping
-- any table whose live sqlite_master DDL already matches reference(1)
-- (idempotent re-run); (3) preflights orphan/NULL/drift guards documented
-- inline above each block before running it; (4) holds
-- PRAGMA foreign_keys=OFF across the ENTIRE transaction (devices has 5 FK
-- children with ON DELETE CASCADE - see file header comment) and restores it
-- ON afterward, outside the transaction; (5) runs PRAGMA integrity_check and
-- PRAGMA foreign_key_check after commit and refuses to report success if
-- either fails.

-- PRAGMA legacy_alter_table=ON is also required (not just FK-off): with it OFF
-- (the modern default), SQLite eagerly re-validates every OTHER schema object
-- that mentions a renamed table's name while executing `ALTER TABLE ... RENAME
-- TO devices` below, and raises a spurious `no such table: main.devices` for
-- device_data's own triggers (they reference `devices` by name) during the
-- instant between DROP TABLE devices and the rename completing - even though
-- foreign key ENFORCEMENT is already off. legacy_alter_table=ON skips that
-- eager re-validation pass entirely (empirically verified 2026-09-11: the
-- fixture in generate-uganda-schema-rebuild-20260911.test.js reproduces the
-- spurious error with this PRAGMA left at its default and passes with it set).

PRAGMA foreign_keys = OFF;
PRAGMA legacy_alter_table = ON;
BEGIN IMMEDIATE;

-- === REBUILD: devices ===
CREATE TABLE devices_rebuild_20260911 (
  id                                    INTEGER PRIMARY KEY AUTOINCREMENT,
  deveui                                TEXT UNIQUE NOT NULL,
  name                                  TEXT NOT NULL,
  type_id                               TEXT NOT NULL CHECK(type_id IN (
                                          'KIWI_SENSOR','STREGA_VALVE','DRAGINO_LSN50',
                                          'TEKTELIC_CLOVER','SENSECAP_S2120','AQUASCOPE_LORAIN')),
  user_id                               INTEGER NULL,
  farm_id                               TEXT NULL,
  current_state                         TEXT CHECK(current_state IN ('OPEN','CLOSED')),
  target_state                          TEXT CHECK(target_state IN ('OPEN','CLOSED')),
  created_at                            TEXT NOT NULL,
  updated_at                            TEXT NOT NULL,
  claimed_at                            TEXT NULL,
  chirpstack_app_id                     TEXT,
  irrigation_zone_id                    INTEGER REFERENCES irrigation_zones(id) ON DELETE SET NULL,
  dendro_enabled                        INTEGER NOT NULL DEFAULT 0,
  temp_enabled                          INTEGER NOT NULL DEFAULT 0,
  is_reference_tree                     INTEGER NOT NULL DEFAULT 0,
  sync_version                          INTEGER DEFAULT 0,
  deleted_at                            DATETIME,
  gateway_device_eui                    TEXT,
  strega_model                          TEXT,
  rain_gauge_enabled                    INTEGER DEFAULT 0,
  flow_meter_enabled                    INTEGER DEFAULT 0,
  soil_moisture_probe_depths_json       TEXT,
  soil_moisture_probe_depths_configured INTEGER DEFAULT 0,
  dendro_ratio_at_retracted             REAL,
  dendro_ratio_at_extended              REAL,
  dendro_force_legacy                   INTEGER DEFAULT 0,
  dendro_stroke_mm                      REAL,
  dendro_ratio_zero                     REAL,
  dendro_ratio_span                     REAL,
  dendro_baseline_position_mm           REAL,
  dendro_baseline_mode_used             TEXT,
  dendro_baseline_calibration_signature TEXT,
  dendro_baseline_pending               INTEGER DEFAULT 0,
  dendro_invert_direction               INTEGER DEFAULT 0,
  device_mode                           INTEGER DEFAULT 1,
  chameleon_enabled                     INTEGER DEFAULT 0,
  chameleon_swt1_depth_cm               REAL,
  chameleon_swt2_depth_cm               REAL,
  chameleon_swt3_depth_cm               REAL,
  FOREIGN KEY (user_id)  REFERENCES users(id)             ON DELETE SET NULL,
  FOREIGN KEY (farm_id)  REFERENCES farms(farm_id)        ON DELETE SET NULL
);

INSERT INTO devices_rebuild_20260911 (
    id,
    deveui,
    name,
    type_id,
    user_id,
    farm_id,
    current_state,
    target_state,
    created_at,
    updated_at,
    claimed_at,
    chirpstack_app_id,
    irrigation_zone_id,
    dendro_enabled,
    temp_enabled,
    is_reference_tree,
    sync_version,
    deleted_at,
    gateway_device_eui,
    strega_model,
    rain_gauge_enabled,
    flow_meter_enabled,
    soil_moisture_probe_depths_json,
    soil_moisture_probe_depths_configured,
    dendro_ratio_at_retracted,
    dendro_ratio_at_extended,
    dendro_force_legacy,
    dendro_stroke_mm,
    dendro_ratio_zero,
    dendro_ratio_span,
    dendro_baseline_position_mm,
    dendro_baseline_mode_used,
    dendro_baseline_calibration_signature,
    dendro_baseline_pending,
    dendro_invert_direction,
    device_mode,
    chameleon_enabled,
    chameleon_swt1_depth_cm,
    chameleon_swt2_depth_cm,
    chameleon_swt3_depth_cm
  )
  SELECT
    id,
    deveui,
    name,
    type_id,
    user_id,
    farm_id,
    current_state,
    target_state,
    created_at,
    updated_at,
    claimed_at,
    chirpstack_app_id,
    irrigation_zone_id,
    dendro_enabled,
    temp_enabled,
    is_reference_tree,
    sync_version,
    deleted_at,
    gateway_device_eui,
    strega_model,
    rain_gauge_enabled,
    flow_meter_enabled,
    soil_moisture_probe_depths_json,
    soil_moisture_probe_depths_configured,
    dendro_ratio_at_retracted,
    dendro_ratio_at_extended,
    dendro_force_legacy,
    dendro_stroke_mm,
    dendro_ratio_zero,
    dendro_ratio_span,
    dendro_baseline_position_mm,
    dendro_baseline_mode_used,
    dendro_baseline_calibration_signature,
    dendro_baseline_pending,
    dendro_invert_direction,
    device_mode,
    chameleon_enabled,
    chameleon_swt1_depth_cm,
    chameleon_swt2_depth_cm,
    chameleon_swt3_depth_cm
  FROM devices;

DROP TABLE devices;
ALTER TABLE devices_rebuild_20260911 RENAME TO devices;

CREATE INDEX idx_devices_user_id          ON devices(user_id);

CREATE INDEX idx_devices_deveui           ON devices(deveui);

CREATE INDEX idx_devices_farm_id          ON devices(farm_id);

CREATE INDEX idx_devices_irrigation_zone_id ON devices(irrigation_zone_id);

DROP TRIGGER IF EXISTS trg_sync_devices_defaults_ai;
CREATE TRIGGER trg_sync_devices_defaults_ai
AFTER INSERT ON devices
FOR EACH ROW
BEGIN
  UPDATE devices
  SET
    gateway_device_eui = COALESCE(gateway_device_eui, '0016C001F11715E2'),
    sync_version       = CASE WHEN COALESCE(sync_version,0)=0 THEN 1 ELSE sync_version END
  WHERE deveui = NEW.deveui;
END;

DROP TRIGGER IF EXISTS trg_sync_devices_outbox_au;
CREATE TRIGGER trg_sync_devices_outbox_au
AFTER UPDATE ON devices
FOR EACH ROW
WHEN
  EXISTS (
    SELECT 1 FROM sync_link_state
     WHERE peer_node = 'cloud' AND linked = 1
  )
  AND (
    COALESCE(NEW.user_id,'') <> COALESCE(OLD.user_id,'') OR
    COALESCE(NEW.irrigation_zone_id,'') <> COALESCE(OLD.irrigation_zone_id,'') OR
    COALESCE(NEW.dendro_enabled,0) <> COALESCE(OLD.dendro_enabled,0) OR
    COALESCE(NEW.temp_enabled,0) <> COALESCE(OLD.temp_enabled,0) OR
    COALESCE(NEW.rain_gauge_enabled,0) <> COALESCE(OLD.rain_gauge_enabled,0) OR
    COALESCE(NEW.flow_meter_enabled,0) <> COALESCE(OLD.flow_meter_enabled,0) OR
    COALESCE(NEW.is_reference_tree,0) <> COALESCE(OLD.is_reference_tree,0) OR
    COALESCE(NEW.name,'') <> COALESCE(OLD.name,'') OR
    COALESCE(NEW.strega_model,'') <> COALESCE(OLD.strega_model,'') OR
    COALESCE(NEW.soil_moisture_probe_depths_json,'') <> COALESCE(OLD.soil_moisture_probe_depths_json,'') OR
    COALESCE(NEW.soil_moisture_probe_depths_configured,0) <> COALESCE(OLD.soil_moisture_probe_depths_configured,0) OR
    COALESCE(NEW.deleted_at,'') <> COALESCE(OLD.deleted_at,'') OR
    COALESCE(NEW.sync_version,0) <> COALESCE(OLD.sync_version,0)
  )
BEGIN
  INSERT INTO sync_outbox(
    event_uuid, aggregate_type, aggregate_key, op, payload_json,
    sync_version, occurred_at, gateway_device_eui
  ) VALUES (
    lower(hex(randomblob(16))),
    'DEVICE',
    NEW.deveui,
    CASE
      WHEN OLD.user_id IS NOT NULL AND NEW.user_id IS NULL THEN 'DEVICE_UNCLAIMED'
      WHEN COALESCE(OLD.irrigation_zone_id,'') <> COALESCE(NEW.irrigation_zone_id,'') AND NEW.irrigation_zone_id IS NULL THEN 'DEVICE_UNASSIGNED'
      WHEN COALESCE(OLD.irrigation_zone_id,'') <> COALESCE(NEW.irrigation_zone_id,'') AND NEW.irrigation_zone_id IS NOT NULL THEN 'DEVICE_ASSIGNED'
      ELSE 'DEVICE_FLAGS_UPDATED'
    END,
    json_object(
      'device_eui',                        NEW.deveui,
      'name',                              NEW.name,
      'type',                              NEW.type_id,
      'claimed_user_uuid',                 (SELECT user_uuid FROM users WHERE id = NEW.user_id),
      'claimed_by_username',               (SELECT COALESCE(server_username,username) FROM users WHERE id = NEW.user_id),
      'zone_uuid',                         (SELECT zone_uuid FROM irrigation_zones WHERE id = NEW.irrigation_zone_id AND deleted_at IS NULL),
      'dendro_enabled',                    NEW.dendro_enabled,
      'temp_enabled',                      NEW.temp_enabled,
      'rain_gauge_enabled',                NEW.rain_gauge_enabled,
      'flow_meter_enabled',                NEW.flow_meter_enabled,
      'is_reference_tree',                 NEW.is_reference_tree,
      'current_state',                     NEW.current_state,
      'target_state',                      NEW.target_state,
      'strega_model',                      NEW.strega_model,
      'soil_moisture_probe_depths_json',   json(COALESCE(NEW.soil_moisture_probe_depths_json,'{}')),
      'soil_moisture_probe_depths_configured', COALESCE(NEW.soil_moisture_probe_depths_configured,0),
      'gateway_device_eui',                COALESCE(NEW.gateway_device_eui,'0016C001F11715E2'),
      'sync_version',                      NEW.sync_version,
      'deleted_at',                        NEW.deleted_at
    ),
    NEW.sync_version,
    strftime('%Y-%m-%dT%H:%M:%fZ','now'),
    COALESCE(NEW.gateway_device_eui,'0016C001F11715E2')
  );
END;

-- === END REBUILD: devices ===
-- === REBUILD: device_data ===
CREATE TABLE device_data_rebuild_20260911 (
  id                        INTEGER PRIMARY KEY AUTOINCREMENT,
  deveui                    TEXT NOT NULL,
  swt_wm1                   REAL,
  swt_wm2                   REAL,
  light_lux                 REAL,
  recorded_at               TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ambient_temperature       REAL,
  relative_humidity         REAL,
  ext_temperature_c         REAL,
  bat_v                     REAL,
  adc_ch0v                  REAL,
  dendro_position_mm        REAL,
  dendro_valid              INTEGER,
  dendro_delta_mm           REAL,
  lsn50_mode_code           INTEGER,
  lsn50_mode_label          TEXT,
  lsn50_mode_observed_at    TEXT,
  rain_mm_per_hour          REAL,
  rain_delta_status         TEXT,
  flow_liters_per_min       REAL,
  rain_mm_per_10min         REAL,
  rain_mm_today             REAL,
  flow_liters_per_10min     REAL,
  flow_liters_today         REAL,
  flow_delta_status         TEXT,
  counter_interval_seconds  INTEGER,
  barometric_pressure_hpa   REAL,
  wind_speed_mps            REAL,
  wind_direction_deg        REAL,
  wind_gust_mps             REAL,
  uv_index                  REAL,
  rain_gauge_cumulative_mm  REAL,
  bat_pct                   REAL,
  rain_count_cumulative     INTEGER,
  rain_tips_delta           INTEGER,
  rain_mm_delta             REAL,
  flow_count_cumulative     INTEGER,
  flow_pulses_delta         INTEGER,
  flow_liters_delta         REAL,
  swt_1                     REAL,
  swt_2                     REAL,
  swt_3                     REAL,
  adc_ch1v                  REAL,
  dendro_ratio              REAL,
  dendro_mode_used          TEXT,
  dendro_stem_change_um     REAL,
  dendro_position_raw_mm    REAL,
  dendro_saturated          INTEGER DEFAULT 0,
  dendro_saturation_side    TEXT,
  FOREIGN KEY (deveui) REFERENCES devices(deveui) ON DELETE CASCADE
);

INSERT INTO device_data_rebuild_20260911 (
    id,
    deveui,
    swt_wm1,
    swt_wm2,
    light_lux,
    recorded_at,
    ambient_temperature,
    relative_humidity,
    ext_temperature_c,
    bat_v,
    adc_ch0v,
    dendro_position_mm,
    dendro_valid,
    dendro_delta_mm,
    lsn50_mode_code,
    lsn50_mode_label,
    lsn50_mode_observed_at,
    rain_mm_per_hour,
    rain_delta_status,
    flow_liters_per_min,
    rain_mm_per_10min,
    rain_mm_today,
    flow_liters_per_10min,
    flow_liters_today,
    flow_delta_status,
    counter_interval_seconds,
    barometric_pressure_hpa,
    wind_speed_mps,
    wind_direction_deg,
    wind_gust_mps,
    uv_index,
    rain_gauge_cumulative_mm,
    bat_pct,
    rain_count_cumulative,
    rain_tips_delta,
    rain_mm_delta,
    flow_count_cumulative,
    flow_pulses_delta,
    flow_liters_delta,
    swt_1,
    swt_2,
    swt_3,
    adc_ch1v,
    dendro_ratio,
    dendro_mode_used,
    dendro_stem_change_um,
    dendro_position_raw_mm,
    dendro_saturated,
    dendro_saturation_side
  )
  SELECT
    id,
    deveui,
    swt_wm1,
    swt_wm2,
    light_lux,
    recorded_at,
    ambient_temperature,
    relative_humidity,
    ext_temperature_c,
    bat_v,
    adc_ch0v,
    dendro_position_mm,
    dendro_valid,
    dendro_delta_mm,
    lsn50_mode_code,
    lsn50_mode_label,
    lsn50_mode_observed_at,
    rain_mm_per_hour,
    rain_delta_status,
    flow_liters_per_min,
    rain_mm_per_10min,
    rain_mm_today,
    flow_liters_per_10min,
    flow_liters_today,
    flow_delta_status,
    counter_interval_seconds,
    barometric_pressure_hpa,
    wind_speed_mps,
    wind_direction_deg,
    wind_gust_mps,
    uv_index,
    rain_gauge_cumulative_mm,
    bat_pct,
    rain_count_cumulative,
    rain_tips_delta,
    rain_mm_delta,
    flow_count_cumulative,
    flow_pulses_delta,
    flow_liters_delta,
    swt_1,
    swt_2,
    swt_3,
    adc_ch1v,
    dendro_ratio,
    dendro_mode_used,
    dendro_stem_change_um,
    dendro_position_raw_mm,
    dendro_saturated,
    dendro_saturation_side
  FROM device_data;

DROP TABLE device_data;
ALTER TABLE device_data_rebuild_20260911 RENAME TO device_data;

CREATE INDEX idx_device_data_deveui      ON device_data(deveui);

CREATE INDEX idx_device_data_recorded_at ON device_data(recorded_at);

CREATE INDEX idx_device_data_deveui_recorded_at ON device_data(deveui, recorded_at);

DROP TRIGGER IF EXISTS trg_dp_device_data_outbox_ai;
CREATE TRIGGER trg_dp_device_data_outbox_ai
AFTER INSERT ON device_data
FOR EACH ROW
WHEN EXISTS (
  SELECT 1 FROM sync_link_state
   WHERE peer_node = 'cloud' AND linked = 1
)
AND COALESCE(
  NULLIF(trim((SELECT gateway_device_eui FROM devices WHERE deveui = NEW.deveui AND deleted_at IS NULL)), ''),
  NULLIF(trim((SELECT gateway_device_eui FROM sync_link_state WHERE peer_node = 'cloud')), '')
) IS NOT NULL
BEGIN
  INSERT INTO sync_outbox(
    event_uuid, aggregate_type, aggregate_key, op, payload_json,
    sync_version, occurred_at, gateway_device_eui
  ) VALUES (
    lower(hex(randomblob(16))),
    'DEVICE_DATA',
    COALESCE(NEW.deveui,'') || '|' || COALESCE(NEW.recorded_at,''),
    'DEVICE_DATA_APPENDED',
    json_object(
      'device_eui',            NEW.deveui,
      'device_name',           (SELECT name    FROM devices WHERE deveui=NEW.deveui AND deleted_at IS NULL),
      'device_type',           (SELECT type_id FROM devices WHERE deveui=NEW.deveui AND deleted_at IS NULL),
      'zone_id',               (SELECT irrigation_zone_id FROM devices WHERE deveui=NEW.deveui AND deleted_at IS NULL),
      'zone_uuid',             (SELECT iz.zone_uuid FROM devices d LEFT JOIN irrigation_zones iz ON iz.id=d.irrigation_zone_id AND iz.deleted_at IS NULL WHERE d.deveui=NEW.deveui AND d.deleted_at IS NULL),
      'gateway_device_eui',    COALESCE((SELECT gateway_device_eui FROM devices WHERE deveui=NEW.deveui AND deleted_at IS NULL),'0016C001F11715E2'),
      'recorded_at',           NEW.recorded_at,
      'swt_wm1',               NEW.swt_wm1,
      'swt_wm2',               NEW.swt_wm2,
      'swt_1',                 NEW.swt_1,
      'swt_2',                 NEW.swt_2,
      'swt_3',                 NEW.swt_3,
      'light_lux',             NEW.light_lux,
      'ambient_temperature',   NEW.ambient_temperature,
      'relative_humidity',     NEW.relative_humidity,
      'ext_temperature_c',     NEW.ext_temperature_c,
      'bat_v',                 NEW.bat_v,
      'adc_ch0v',              NEW.adc_ch0v,
      'dendro_position_mm',    NEW.dendro_position_mm,
      'dendro_valid',          NEW.dendro_valid,
      'dendro_delta_mm',       NEW.dendro_delta_mm,
      'dendro_stem_change_um', NEW.dendro_stem_change_um,
      'adc_ch1v',              NEW.adc_ch1v,
      'dendro_ratio',          NEW.dendro_ratio,
      'dendro_mode_used',      NEW.dendro_mode_used,
      'lsn50_mode_code',       NEW.lsn50_mode_code,
      'lsn50_mode_label',      NEW.lsn50_mode_label,
      'lsn50_mode_observed_at', NEW.lsn50_mode_observed_at,
      'rain_count_cumulative', NEW.rain_count_cumulative,
      'rain_tips_delta',       NEW.rain_tips_delta,
      'rain_mm_delta',         NEW.rain_mm_delta,
      'rain_mm_per_hour',      NEW.rain_mm_per_hour,
      'rain_mm_per_10min',     NEW.rain_mm_per_10min,
      'rain_mm_today',         NEW.rain_mm_today,
      'rain_delta_status',     NEW.rain_delta_status,
      'flow_count_cumulative', NEW.flow_count_cumulative,
      'flow_pulses_delta',     NEW.flow_pulses_delta,
      'flow_liters_delta',     NEW.flow_liters_delta,
      'flow_liters_per_min',   NEW.flow_liters_per_min,
      'flow_liters_per_10min', NEW.flow_liters_per_10min,
      'flow_liters_today',     NEW.flow_liters_today,
      'flow_delta_status',     NEW.flow_delta_status,
      'counter_interval_seconds', NEW.counter_interval_seconds,
      'barometric_pressure_hpa',  NEW.barometric_pressure_hpa,
      'wind_speed_mps',        NEW.wind_speed_mps,
      'wind_direction_deg',    NEW.wind_direction_deg,
      'wind_gust_mps',         NEW.wind_gust_mps,
      'uv_index',              NEW.uv_index,
      'rain_gauge_cumulative_mm', NEW.rain_gauge_cumulative_mm,
      'bat_pct',               NEW.bat_pct
    ),
    0,
    strftime('%Y-%m-%dT%H:%M:%fZ','now'),
    COALESCE((SELECT gateway_device_eui FROM devices WHERE deveui=NEW.deveui AND deleted_at IS NULL),'0016C001F11715E2')
  );
END;

DROP TRIGGER IF EXISTS trg_sync_device_data_dirty_au;
CREATE TRIGGER trg_sync_device_data_dirty_au
AFTER UPDATE ON device_data
FOR EACH ROW
WHEN EXISTS (
  SELECT 1 FROM sync_link_state
   WHERE peer_node = 'cloud' AND linked = 1
)
AND COALESCE((SELECT gateway_device_eui FROM devices WHERE deveui = NEW.deveui AND deleted_at IS NULL), (SELECT gateway_device_eui FROM sync_link_state WHERE peer_node = 'cloud'), '') <> ''
BEGIN
  INSERT INTO sync_history_dirty_keys(peer_node, table_name, row_key, change_kind, source_row_id, changed_at)
  VALUES(
    'cloud',
    'device_data',
    'DEVICE_DATA|' || COALESCE((SELECT gateway_device_eui FROM devices WHERE deveui = NEW.deveui AND deleted_at IS NULL), (SELECT gateway_device_eui FROM sync_link_state WHERE peer_node = 'cloud'), '') || '|' || NEW.id,
    'correction',
    NEW.id,
    strftime('%Y-%m-%dT%H:%M:%fZ','now')
  )
  ON CONFLICT(peer_node, table_name, row_key) DO UPDATE SET
    change_kind = excluded.change_kind,
    source_row_id = excluded.source_row_id,
    changed_at = excluded.changed_at,
    status = 'pending',
    attempts = 0,
    next_attempt_at = NULL,
    last_error = NULL;
END;

DROP TRIGGER IF EXISTS sync_dendro_to_readings;
CREATE TRIGGER sync_dendro_to_readings
AFTER INSERT ON device_data
WHEN NEW.dendro_position_mm IS NOT NULL
BEGIN
  INSERT OR IGNORE INTO dendrometer_readings(
    deveui, position_um, adc_v, adc_ch0v, adc_ch1v,
    dendro_ratio, dendro_mode_used, bat_v, is_valid, recorded_at
  ) VALUES (
    NEW.deveui,
    ROUND(NEW.dendro_position_mm * 1000),
    NEW.adc_ch0v, NEW.adc_ch0v, NEW.adc_ch1v,
    NEW.dendro_ratio, NEW.dendro_mode_used,
    NEW.bat_v, COALESCE(NEW.dendro_valid, 1), NEW.recorded_at
  );
END;

-- === END REBUILD: device_data ===
-- === ALTER: irrigation_events (no rebuild needed - event_uuid is a plain nullable column; see design doc) ===
ALTER TABLE irrigation_events ADD COLUMN event_uuid TEXT;

CREATE UNIQUE INDEX idx_irrigation_events_event_uuid ON irrigation_events(event_uuid);

-- === END ALTER: irrigation_events ===
-- === REBUILD: valve_actuation_expectations ===
CREATE TABLE valve_actuation_expectations_rebuild_20260911 (
  expectation_id             TEXT PRIMARY KEY,
  device_eui                 TEXT NOT NULL,
  zone_id                    INTEGER,
  command_id                 TEXT,
  effect_key                 TEXT,
  commanded_at               TEXT NOT NULL,
  commanded_duration_seconds INTEGER NOT NULL,
  expected_close_at          TEXT NOT NULL,
  flow_rate_lpm              REAL,
  flow_rate_source           TEXT,
  estimated_gross_liters     REAL,
  volume_source              TEXT NOT NULL,
  observed_open_at           TEXT,
  observed_close_at          TEXT,
  reconciliation_state       TEXT NOT NULL DEFAULT 'PENDING_OBSERVATION',
  cancel_reason              TEXT,
  created_at                 TEXT NOT NULL
);

INSERT INTO valve_actuation_expectations_rebuild_20260911 (
    expectation_id,
    device_eui,
    zone_id,
    command_id,
    effect_key,
    commanded_at,
    commanded_duration_seconds,
    expected_close_at,
    flow_rate_lpm,
    flow_rate_source,
    estimated_gross_liters,
    volume_source,
    observed_open_at,
    observed_close_at,
    reconciliation_state,
    cancel_reason,
    created_at
  )
  SELECT
    expectation_id,
    device_eui,
    zone_id,
    command_id,
    effect_key,
    commanded_at,
    commanded_duration_seconds,
    expected_close_at,
    flow_rate_lpm,
    flow_rate_source,
    estimated_gross_liters,
    volume_source,
    observed_open_at,
    observed_close_at,
    reconciliation_state,
    cancel_reason,
    created_at
  FROM valve_actuation_expectations;

DROP TABLE valve_actuation_expectations;
ALTER TABLE valve_actuation_expectations_rebuild_20260911 RENAME TO valve_actuation_expectations;

CREATE INDEX idx_valve_act_exp_device_eui ON valve_actuation_expectations(device_eui);

CREATE INDEX idx_valve_act_exp_active
  ON valve_actuation_expectations(reconciliation_state)
  WHERE reconciliation_state IN ('PENDING_OBSERVATION','OBSERVED_RUNNING');

CREATE INDEX idx_valve_act_exp_effect_key ON valve_actuation_expectations(effect_key);

-- === END REBUILD: valve_actuation_expectations ===
-- === REBUILD: zone_irrigation_calibration ===
CREATE TABLE zone_irrigation_calibration_rebuild_20260911 (
  zone_id                INTEGER PRIMARY KEY,
  valve_device_eui       TEXT,
  measured_flow_rate_lpm REAL NOT NULL,
  measurement_method     TEXT NOT NULL,
  measured_at            TEXT NOT NULL,
  created_at             TEXT NOT NULL,
  updated_at             TEXT NOT NULL
);

INSERT INTO zone_irrigation_calibration_rebuild_20260911 (
    zone_id,
    valve_device_eui,
    measured_flow_rate_lpm,
    measurement_method,
    measured_at,
    created_at,
    updated_at
  )
  SELECT
    zone_id,
    valve_device_eui,
    measured_flow_rate_lpm,
    measurement_method,
    measured_at,
    created_at,
    updated_at
  FROM zone_irrigation_calibration;

DROP TABLE zone_irrigation_calibration;
ALTER TABLE zone_irrigation_calibration_rebuild_20260911 RENAME TO zone_irrigation_calibration;

-- === END REBUILD: zone_irrigation_calibration ===
-- === REBUILD: zone_weather_cache ===
CREATE TABLE zone_weather_cache_rebuild_20260911 (
  zone_id      INTEGER NOT NULL,
  cache_key    TEXT NOT NULL,
  source       TEXT,
  payload_json TEXT NOT NULL,
  observed_at  TEXT,
  fetched_at   TEXT NOT NULL,
  expires_at   TEXT NOT NULL,
  PRIMARY KEY (zone_id, cache_key),
  FOREIGN KEY (zone_id) REFERENCES irrigation_zones(id) ON DELETE CASCADE
);

INSERT INTO zone_weather_cache_rebuild_20260911 (
    zone_id,
    cache_key,
    source,
    payload_json,
    observed_at,
    fetched_at,
    expires_at
  )
  SELECT
    zone_id,
    cache_key,
    source,
    payload_json,
    observed_at,
    created_at,
    expires_at
  FROM zone_weather_cache;

DROP TABLE zone_weather_cache;
ALTER TABLE zone_weather_cache_rebuild_20260911 RENAME TO zone_weather_cache;

-- === END REBUILD: zone_weather_cache ===

COMMIT;
PRAGMA foreign_keys = ON;
PRAGMA legacy_alter_table = OFF;
