#!/bin/sh /etc/rc.common

START=101
STOP=20

USE_PROCD=1

SERVICE_NAME=osi-gateway-gps
PROG=/usr/bin/node
SCRIPT=/usr/bin/osi-gateway-gps.js

start_service() {
	local enabled
	local device_eui

	config_load osi-gateway-gps
	config_get_bool enabled core enabled 1
	[ "$enabled" -eq 1 ] || return 1

	device_eui="$(uci -q get osi-server.cloud.device_eui 2>/dev/null || echo "")"

	procd_open_instance
	procd_set_param command "$PROG" "$SCRIPT"
	procd_set_param env DEVICE_EUI="$device_eui"
	procd_set_param respawn 3600 5 -1
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger osi-gateway-gps gpsd osi-server chirpstack-concentratord
}
