DROP TRIGGER jobs_publish_guard;
DROP TRIGGER jobs_publish_guard_insert;

CREATE TRIGGER jobs_publish_guard
BEFORE UPDATE OF artifact_staging_path, artifact_quarantine_path, artifact_quarantine_intent_path, artifact_final_directory, artifact_final_path, artifact_sha256, artifact_size, artifact_mtime, checksum_path, checksum_sha256, manifest_path, manifest_sha256, verification_path, verification_sha256, publish_state, publish_started_at, published_at, publish_blocker_code, publish_blocker_json ON jobs
WHEN NEW.publish_state IS NOT NULL
BEGIN
  SELECT CASE WHEN NOT (
    (NEW.publish_state = 'not_started' AND (
      (NEW.artifact_staging_path IS NULL AND NEW.artifact_sha256 IS NULL AND NEW.artifact_size IS NULL AND NEW.artifact_mtime IS NULL AND NEW.checksum_path IS NULL AND NEW.checksum_sha256 IS NULL AND NEW.manifest_path IS NULL AND NEW.manifest_sha256 IS NULL AND NEW.verification_path IS NULL AND NEW.verification_sha256 IS NULL)
      OR
      (NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL)
    ) AND NEW.artifact_quarantine_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'staged' AND NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.artifact_quarantine_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'publishing' AND NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.artifact_final_directory IS NOT NULL AND NEW.artifact_final_path IS NOT NULL AND NEW.publish_started_at IS NOT NULL AND NEW.published_at IS NULL AND NEW.artifact_quarantine_path IS NULL AND (NEW.artifact_quarantine_intent_path IS NULL OR NEW.artifact_quarantine_intent_path = '.osi-image-builder/quarantine/' || NEW.job_id) AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'published' AND NEW.artifact_staging_path IS NULL AND NEW.artifact_final_directory IS NOT NULL AND NEW.artifact_final_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.publish_started_at IS NOT NULL AND NEW.published_at IS NOT NULL AND NEW.artifact_quarantine_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'quarantined' AND NEW.artifact_quarantine_path IS NOT NULL AND NEW.artifact_staging_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'blocked' AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.publish_blocker_code IS NOT NULL AND NEW.publish_blocker_json IS NOT NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NOT (NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_quarantine_path IS NOT NULL))
  ) THEN RAISE(ABORT, 'publish result is incoherent') END;
END;

CREATE TRIGGER jobs_publish_guard_insert
BEFORE INSERT ON jobs
WHEN NEW.publish_state IS NOT NULL
BEGIN
  SELECT CASE WHEN NOT (
    (NEW.publish_state = 'not_started' AND (
      (NEW.artifact_staging_path IS NULL AND NEW.artifact_sha256 IS NULL AND NEW.artifact_size IS NULL AND NEW.artifact_mtime IS NULL AND NEW.checksum_path IS NULL AND NEW.checksum_sha256 IS NULL AND NEW.manifest_path IS NULL AND NEW.manifest_sha256 IS NULL AND NEW.verification_path IS NULL AND NEW.verification_sha256 IS NULL)
      OR
      (NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL)
    ) AND NEW.artifact_quarantine_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'staged' AND NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.artifact_quarantine_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'publishing' AND NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.artifact_final_directory IS NOT NULL AND NEW.artifact_final_path IS NOT NULL AND NEW.publish_started_at IS NOT NULL AND NEW.published_at IS NULL AND NEW.artifact_quarantine_path IS NULL AND (NEW.artifact_quarantine_intent_path IS NULL OR NEW.artifact_quarantine_intent_path = '.osi-image-builder/quarantine/' || NEW.job_id) AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'published' AND NEW.artifact_staging_path IS NULL AND NEW.artifact_final_directory IS NOT NULL AND NEW.artifact_final_path IS NOT NULL AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.publish_started_at IS NOT NULL AND NEW.published_at IS NOT NULL AND NEW.artifact_quarantine_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'quarantined' AND NEW.artifact_quarantine_path IS NOT NULL AND NEW.artifact_staging_path IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.publish_blocker_code IS NULL AND NEW.publish_blocker_json IS NULL)
    OR (NEW.publish_state = 'blocked' AND NEW.artifact_sha256 IS NOT NULL AND NEW.artifact_size IS NOT NULL AND NEW.artifact_mtime IS NOT NULL AND NEW.checksum_path IS NOT NULL AND NEW.checksum_sha256 IS NOT NULL AND NEW.manifest_path IS NOT NULL AND NEW.manifest_sha256 IS NOT NULL AND NEW.verification_path IS NOT NULL AND NEW.verification_sha256 IS NOT NULL AND NEW.publish_blocker_code IS NOT NULL AND NEW.publish_blocker_json IS NOT NULL AND NEW.artifact_final_directory IS NULL AND NEW.artifact_final_path IS NULL AND NEW.publish_started_at IS NULL AND NEW.published_at IS NULL AND NEW.artifact_quarantine_intent_path IS NULL AND NOT (NEW.artifact_staging_path IS NOT NULL AND NEW.artifact_quarantine_path IS NOT NULL))
  ) THEN RAISE(ABORT, 'publish result is incoherent') END;
END;
