import { createHash } from 'node:crypto';
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, stat, symlink, unlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

import { OwnershipStore } from '../../api/src/ownership.js';
import { createCleanupAdmissionRecovery } from '../../api/src/recovery.js';
import { openBuilderDatabase } from '../../api/src/store-schema.js';

const NOW = '2026-07-27T12:00:00.000Z'; const EXPIRES = '2026-07-27T12:05:00.000Z'; const SHA40 = 'a'.repeat(40); const SHA64 = 'b'.repeat(64); const roots: string[] = [];
function snapshot(jobId: string) { return { runner: { unit: `osi-image-builder-runner@${jobId}.service`, owner: null, leaseExpiresAt: null, inactiveAt: NOW, observedAt: NOW }, state: 'starting' as const, container: { kind: 'absent' as const, globalLabelResult: 'no-match' as const, observedAt: NOW }, staging: { kind: 'absent' as const, path: null }, logs: { runner: 'absent' as const, docker: 'absent' as const, verifiedAt: NOW }, blocker: 'none' as const }; }

async function fixture() {
  const root = await mkdtemp(join(tmpdir(), 'osi-cleanup-crash-')); roots.push(root); const db = openBuilderDatabase(join(root, 'jobs.sqlite')); const ownership = new OwnershipStore(db, { now: () => NOW }); const jobId = 'job-crash';
  expect(ownership.apiWrite({ kind: 'enqueue', input: { jobId, requestId: 'request-crash', request: { branch: 'main', target: 'rpi-5' }, sourceRemote: 'git@example.com:osi-os.git', sourceRef: 'refs/remotes/origin/main', sourceBranch: 'main', branch: 'main', expectedSha: SHA40, pinnedSha: SHA40, sourcePreparation: { schemaVersion: 1 as const, sourceSha: SHA40, gitmodulesBlobSha: 'c'.repeat(40), preparedAt: NOW, components: [{ path: 'feeds/chirpstack-openwrt-feed' as const, mode: '040000' as const, type: 'tree' as const, objectId: 'd'.repeat(40), provenanceUrl: 'https://github.com/chirpstack/chirpstack-openwrt-feed.git' }, { path: 'openwrt' as const, mode: '040000' as const, type: 'tree' as const, objectId: 'e'.repeat(40), provenanceUrl: 'https://github.com/openwrt/openwrt.git' }] }, offlineFeedPreparation: { schemaVersion: 1 as const, boundary: 'api-prepared-pinned-feeds-v1' as const, networkPolicy: 'runner-offline' as const, jobId, sourceSha: SHA40, preparedAt: NOW, feeds: [{ name: 'packages', location: 'https://git.openwrt.org/feed/packages.git', commit: 'd8cd30f4e281d6853b3de134c4f147a807583e43', detached: true as const, clean: true as const, recursiveSubmodulesPrepared: true as const, recursiveSubmodules: [], recursiveSubmoduleStatusSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', treeSha256: SHA64 }, { name: 'luci', location: 'https://git.openwrt.org/project/luci.git', commit: '2ac26e56cc55102cb10e7b0867c2b78e0f6d5fd8', detached: true as const, clean: true as const, recursiveSubmodulesPrepared: true as const, recursiveSubmodules: [], recursiveSubmoduleStatusSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', treeSha256: SHA64 }, { name: 'routing', location: 'https://git.openwrt.org/feed/routing.git', commit: 'c9b636698881059a3c981032770968f5a98ff201', detached: true as const, clean: true as const, recursiveSubmodulesPrepared: true as const, recursiveSubmodules: [], recursiveSubmoduleStatusSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', treeSha256: SHA64 }] }, targetId: 'rpi-5', rootId: 'release', targetManifestSha256: SHA64, sourceCommitTime: NOW, sourceAuthor: 'Builder', sourceSubject: 'cleanup crash', acceptedAt: NOW } }).ok).toBe(true); expect(ownership.apiWrite({ kind: 'dispatch', jobId, runnerUnit: `osi-image-builder-runner@${jobId}.service`, at: NOW }).ok).toBe(true); return { root, db, ownership, jobId };
}
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });

describe('cleanup credential crash boundaries', () => {
  it('leaves a durable orphan after admission commit failure and prunes it only after restart proves no row', async () => {
    const value = await fixture(); const recovery = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: { apiWrite: () => { throw new Error('simulated admission commit crash'); } }, systemd: { start: async () => { throw new Error('worker must not start'); }, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 });
    await expect(recovery.admitAndStart({ jobId: value.jobId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) })).rejects.toThrow('simulated admission commit crash'); const credentialRoot = join(value.root, 'jobs', value.jobId, 'recovery', 'cleanup-credentials'); const files = await readdir(credentialRoot); expect(files).toHaveLength(1); expect(files[0]).toMatch(/^cln_[0-9a-hj-km-np-tv-z]{26}\.token$/); expect((await stat(join(credentialRoot, files[0]!))).mode & 0o777).toBe(0o600);
    const restarted = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: value.ownership, systemd: { start: async () => undefined, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 }); expect(await restarted.pruneOrphanCredentials()).toEqual(1); expect(await readdir(credentialRoot)).toEqual([]); value.db.close();
  });

  it('commits the fence and lease before starting the exact worker, with no plaintext token in SQLite', async () => {
    const value = await fixture(); const chronology: string[] = []; const recovery = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: { apiWrite: (command) => { const result = value.ownership.apiWrite(command); if (result.ok) chronology.push('db:commit'); return result; } }, systemd: { start: async (unit) => { chronology.push(`systemd:${unit}`); expect(value.db.prepare('SELECT cleanup_admission_id, cleanup_fence_generation FROM jobs WHERE job_id=?').get(value.jobId)).toMatchObject({ cleanup_fence_generation: 1 }); }, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 });
    const result = await recovery.admitAndStart({ jobId: value.jobId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) }); const lease = value.db.prepare('SELECT * FROM cleanup_leases WHERE admission_id=?').get(result.admissionId) as Record<string, unknown>; expect(chronology).toEqual(['db:commit', `systemd:${result.unitName}`]); expect(lease).toMatchObject({ job_id: value.jobId, status: 'admitted', fence_generation: 1, unit_name: result.unitName }); expect(lease.credential_sha256).toBe(createHash('sha256').update(await readFile(join(value.root, 'jobs', value.jobId, result.credentialRelativePath))).digest('hex')); expect(await recovery.pruneOrphanCredentials()).toBe(0); value.db.close();
  });

  it('does not prune symlink credential entries', async () => {
    const value = await fixture(); const credentialRoot = join(value.root, 'jobs', value.jobId, 'recovery', 'cleanup-credentials'); await mkdir(credentialRoot, { recursive: true, mode: 0o700 }); await mkdir(join(value.root, 'outside'), { mode: 0o700 }); const unsafe = join(credentialRoot, 'cln_00000000000000000000000000.token'); await symlink(join(value.root, 'outside'), unsafe); const recovery = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: value.ownership, systemd: { start: async () => undefined, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 }); expect(await recovery.pruneOrphanCredentials()).toBe(0); await expect(stat(unsafe)).resolves.toBeDefined(); value.db.close();
  });

  it('does not prune ambiguous or wrong-mode credential entries', async () => {
    const value = await fixture(); const credentialRoot = join(value.root, 'jobs', value.jobId, 'recovery', 'cleanup-credentials'); await mkdir(credentialRoot, { recursive: true, mode: 0o700 }); const wrongMode = join(credentialRoot, 'cln_00000000000000000000000000.token'); const ambiguous = join(credentialRoot, 'not-an-admission.token'); await writeFile(wrongMode, 'not a credential\n', { mode: 0o644 }); await writeFile(ambiguous, 'not a credential\n', { mode: 0o600 }); const recovery = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: value.ownership, systemd: { start: async () => undefined, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 }); expect(await recovery.pruneOrphanCredentials()).toBe(0); await expect(stat(wrongMode)).resolves.toBeDefined(); await expect(stat(ambiguous)).resolves.toBeDefined(); await chmod(wrongMode, 0o600); value.db.close();
  });

  it('rotates the committed fence atomically to a new generation and rejects the stale predecessor', async () => {
    const value = await fixture(); const starts: string[] = []; const recovery = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: value.ownership, systemd: { start: async (unit) => { starts.push(unit); }, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 });
    const first = await recovery.admitAndStart({ jobId: value.jobId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) }); const oldPath = join(value.root, 'jobs', value.jobId, first.credentialRelativePath); const oldRecord = JSON.parse(await readFile(oldPath, 'utf8')) as { token: string };
    await unlink(oldPath); const rotated = await recovery.reconcileAndStart({ jobId: value.jobId, admissionId: first.admissionId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) });
    expect(rotated.generation).toBe(2); expect(rotated.admissionId).not.toBe(first.admissionId); expect(starts).toEqual([first.unitName, rotated.unitName]); expect(recovery.verifyToken(oldRecord.token, first.admissionId)).toBe(false);
    expect(value.db.prepare('SELECT admission_id, status, fence_generation FROM cleanup_leases WHERE job_id=? ORDER BY fence_generation').all(value.jobId)).toEqual([
      expect.objectContaining({ admission_id: first.admissionId, status: 'expired', fence_generation: 1 }),
      expect.objectContaining({ admission_id: rotated.admissionId, status: 'admitted', fence_generation: 2 }),
    ]); expect(value.db.prepare('SELECT cleanup_generation, cleanup_admission_id, cleanup_fence_generation FROM jobs WHERE job_id=?').get(value.jobId)).toMatchObject({ cleanup_generation: 2, cleanup_admission_id: rotated.admissionId, cleanup_fence_generation: 2 });
    await expect(recovery.reconcileAndStart({ jobId: value.jobId, admissionId: first.admissionId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) })).rejects.toThrow('not rotatable'); value.db.close();
  });

  it('rolls back rotation at the database boundary and keeps the old fence', async () => {
    const value = await fixture(); const initial = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: value.ownership, systemd: { start: async () => undefined, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 }); const first = await initial.admitAndStart({ jobId: value.jobId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) }); await unlink(join(value.root, 'jobs', value.jobId, first.credentialRelativePath));
    const failing = new OwnershipStore(value.db, { now: () => NOW, failBeforeCommit: () => { throw new Error('database commit failure'); } }); const recovery = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: failing, systemd: { start: async () => { throw new Error('worker must not start'); }, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 }); await expect(recovery.reconcileAndStart({ jobId: value.jobId, admissionId: first.admissionId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) })).rejects.toThrow('SQLite ownership transaction rolled back'); expect(value.db.prepare('SELECT status FROM cleanup_leases WHERE admission_id=?').get(first.admissionId)).toMatchObject({ status: 'admitted' }); expect(value.db.prepare('SELECT cleanup_admission_id, cleanup_fence_generation FROM jobs WHERE job_id=?').get(value.jobId)).toMatchObject({ cleanup_admission_id: first.admissionId, cleanup_fence_generation: 1 }); value.db.close();
  });

  it('keeps the replacement admission fenced when the exact systemd start fails', async () => {
    const value = await fixture(); let starts = 0; const recovery = createCleanupAdmissionRecovery({ stateRoot: value.root, db: value.db, ownership: value.ownership, systemd: { start: async () => { starts += 1; if (starts === 2) throw new Error('systemd start failure'); }, isActive: async () => false }, clock: { now: () => NOW }, ownerUid: process.getuid?.() ?? 0 }); const first = await recovery.admitAndStart({ jobId: value.jobId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) }); await unlink(join(value.root, 'jobs', value.jobId, first.credentialRelativePath));
    await expect(recovery.reconcileAndStart({ jobId: value.jobId, admissionId: first.admissionId, owner: 'api', expiresAt: EXPIRES, at: NOW, snapshot: snapshot(value.jobId) })).rejects.toThrow('systemd start failure'); const job = value.db.prepare('SELECT cleanup_admission_id, cleanup_fence_generation FROM jobs WHERE job_id=?').get(value.jobId) as { cleanup_admission_id: string; cleanup_fence_generation: number }; expect(job.cleanup_admission_id).not.toBe(first.admissionId); expect(job.cleanup_fence_generation).toBe(2); expect(value.db.prepare('SELECT status FROM cleanup_leases WHERE admission_id=?').get(first.admissionId)).toMatchObject({ status: 'expired' }); value.db.close();
  });
});
