import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import type React from 'react';
import { Link } from 'react-router-dom';
import { CircleMarker, MapContainer, Popup, Polyline, TileLayer, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { devicesAPI, networkAPI, type InstallationLocationRevision, type RadioConfigurationRevision, type NetworkObservation } from '../services/api';
import type { Device } from '../types/farming';

const fallback = (key: string, value: string) => ({ defaultValue: value, key });
type Position = { lat: number; lon: number };
type ParsedObservation = { observation: NetworkObservation; device: Position | null; receivers: Array<Position & { id: string }> };
const parsePosition = (value: any): Position | null => { if (value?.latitude == null || value?.longitude == null || value?.latitude === '' || value?.longitude === '') return null; const lat = Number(value.latitude); const lon = Number(value.longitude); return Number.isFinite(lat) && Number.isFinite(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180 ? { lat, lon } : null; };
export const parseObservation = (observation: NetworkObservation): ParsedObservation => { try { const metadata = JSON.parse(observation.metadata_json ?? '{}'); const receivers = (Array.isArray(metadata.receivers) ? metadata.receivers : []).flatMap((receiver: any) => { const point = parsePosition(receiver?.position); return point ? [{ ...point, id: String(receiver?.gateway_id ?? 'unknown') }] : []; }); return { observation, device: parsePosition(metadata.reported_position) ?? parsePosition(metadata.device_location), receivers }; } catch { return { observation, device: null, receivers: [] }; } };
function FitBounds({ points }: { points: Position[] }) { const map = useMap(); useEffect(() => { if (points.length) map.fitBounds(points.map(point => [point.lat, point.lon] as [number, number]), { padding: [24, 24] }); }, [map, points]); return null; }
const observationRssi = (observation: NetworkObservation) => {
  if (observation.rssi != null) return observation.rssi;
  try { const receivers = JSON.parse(observation.metadata_json ?? '{}').receivers; return Array.isArray(receivers) ? receivers.find((receiver: any) => receiver?.rssi_dbm != null)?.rssi_dbm ?? null : null; } catch { return null; }
};

export function NetworkPage() {
  const { t } = useTranslation('network');
  const [windowBounds, setWindowBounds] = useState<{ from: string; to: string } | undefined>();
  const [devices, setDevices] = useState<Device[]>([]); const [selected, setSelected] = useState('');
  const [location, setLocation] = useState<InstallationLocationRevision | null>(null); const [radio, setRadio] = useState<RadioConfigurationRevision | null>(null);
  const [observations, setObservations] = useState<NetworkObservation[]>([]); const [nextOffset, setNextOffset] = useState<number | null>(null); const [error, setError] = useState<string | null>(null); const [paused, setPaused] = useState(false); const [loadingMore, setLoadingMore] = useState(false);
  useEffect(() => { devicesAPI.getAll().then(value => { setDevices(value); if (value[0]) setSelected(value[0].deveui); }).catch(() => setError(t('network.loadError', fallback('loadError', 'Could not load devices')))); }, [t]);
  useEffect(() => {
    if (!selected) return;
    let active = true;
    setError(null); setLocation(null); setRadio(null);
    networkAPI.location(selected).then(value => { if (active) setLocation(value); }).catch(() => { if (active) setLocation(null); });
    networkAPI.radio(selected).then(value => { if (active) setRadio(value); }).catch(() => { if (active) setRadio(null); });
    networkAPI.observations().then(page => {
      if (!active) return;
      setObservations(page.rows); setWindowBounds({ from: page.from, to: page.to }); setNextOffset(page.nextOffset); setPaused(false);
    }).catch((e: any) => { if (active) { setPaused(e?.response?.status === 503); setError(t('network.unavailable', fallback('unavailable', 'Network data temporarily unavailable'))); } });
    return () => { active = false; };
  }, [selected, t]);
  const loadMore = async () => { if (nextOffset === null || loadingMore) return; setLoadingMore(true); try { const page = await networkAPI.observations(Math.min(500, 5000 - observations.length), nextOffset, windowBounds); setObservations(rows => [...rows, ...page.rows]); setNextOffset(observations.length + page.rows.length >= 5000 ? null : page.nextOffset); } catch (e: any) { setError(t('network.unavailable', fallback('unavailable', 'Network data temporarily unavailable'))); } finally { setLoadingMore(false); } };
  const saveLocation = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); try { const value = await networkAPI.saveLocation(selected, { revision_uuid: crypto.randomUUID(), base_revision_uuid: location?.revisionUuid ?? null, values: { latitude: Number(data.get('latitude')), longitude: Number(data.get('longitude')), effectiveFrom: new Date().toISOString(), coordinateSource: 'manual' } }); setLocation(value); setError(null); } catch (e: any) { setError(e?.response?.status === 409 ? t('network.conflict', fallback('conflict', 'This record changed. Reload before saving.')) : t('network.saveError', fallback('saveError', 'Could not save'))); } };
  const saveRadio = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); try { const value = await networkAPI.saveRadio(selected, { revision_uuid: crypto.randomUUID(), base_revision_uuid: radio?.revisionUuid ?? null, values: { txPowerDbm: data.get('txPowerDbm') === '' ? null : Number(data.get('txPowerDbm')), antennaGainDbi: data.get('antennaGainDbi') === '' ? null : Number(data.get('antennaGainDbi')), feederLossDb: data.get('feederLossDb') === '' ? null : Number(data.get('feederLossDb')), effectiveFrom: new Date().toISOString(), configurationSource: 'manual' } }); setRadio(value); setError(null); } catch (e: any) { setError(e?.response?.status === 409 ? t('network.conflict', fallback('conflict', 'This record changed. Reload before saving.')) : t('network.saveError', fallback('saveError', 'Could not save'))); } };
  const parsed = observations.map(parseObservation); const snapshots = parsed.flatMap(item => item.device ? [{ ...item.device, label: item.observation.deveui }] : []); const known = [...(location ? [{ lat: location.latitude, lon: location.longitude, label: selected }] : []), ...snapshots];
  return <main className="mx-auto max-w-6xl p-6"><nav className="mb-4 flex gap-3 text-sm"><Link to="/dashboard" className="underline">{t('network.dashboard', fallback('dashboard', 'Dashboard'))}</Link><Link to="/network" aria-current="page" className="font-semibold">{t('network.title', fallback('title', 'Network observations'))}</Link></nav><h1 className="text-2xl font-bold">{t('network.title', fallback('title', 'Network observations'))}</h1>
    {error && <p role="alert" className="my-4 rounded border border-red-300 p-3">{error}</p>}{paused && <p className="my-4 rounded border border-amber-300 p-3">{t('network.paused', fallback('paused', 'Updates paused'))}</p>}
    <label className="mt-5 block">{t('network.device', fallback('device', 'Device'))} <select value={selected} onChange={e => setSelected(e.target.value)} className="ml-2 rounded border p-2">{devices.map(d => <option key={d.deveui} value={d.deveui}>{d.name} ({d.deveui})</option>)}</select></label>
    <section key={`${selected}-${location?.revisionUuid ?? 'new'}-${radio?.revisionUuid ?? 'new'}`} className="mt-6 grid gap-5 md:grid-cols-2"><form key={`${selected}-${location?.revisionUuid ?? 'new'}`} onSubmit={saveLocation} className="rounded border p-4"><h2 className="font-semibold">{t('network.location', fallback('location', 'Installed location'))}</h2><input name="latitude" type="number" min="-90" max="90" step="any" defaultValue={location?.latitude ?? ''} placeholder={t('network.latitude', fallback('latitude', 'Latitude'))} className="mr-2 mt-3 rounded border p-2" required /><input name="longitude" type="number" min="-180" max="180" step="any" defaultValue={location?.longitude ?? ''} placeholder={t('network.longitude', fallback('longitude', 'Longitude'))} className="mt-3 rounded border p-2" required /><button className="mt-3 block rounded bg-blue-700 px-3 py-2 text-white">{t('network.save', fallback('save', 'Save'))}</button><p className="mt-2 text-sm">{location ? `${location.coordinateSource} · ${location.effectiveFrom}` : t('network.unknown', fallback('unknown', 'Unknown'))}</p></form>
    <form key={`${selected}-${radio?.revisionUuid ?? 'new'}`} onSubmit={saveRadio} className="rounded border p-4"><h2 className="font-semibold">{t('network.radio', fallback('radio', 'Radio configuration'))}</h2><input name="txPowerDbm" type="number" step="any" defaultValue={radio?.txPowerDbm ?? ''} placeholder={t('network.txPower', fallback('txPower', 'TX power (dBm)'))} className="mr-2 mt-3 rounded border p-2" /><input name="antennaGainDbi" type="number" min="0" max="13" step="any" defaultValue={radio?.antennaGainDbi ?? ''} placeholder={t('network.gain', fallback('gain', 'Antenna gain (dBi)'))} className="mr-2 mt-3 rounded border p-2" /><input name="feederLossDb" type="number" min="0" step="any" defaultValue={radio?.feederLossDb ?? ''} placeholder={t('network.loss', fallback('loss', 'Feeder loss (dB)'))} className="mt-3 rounded border p-2" /><button className="mt-3 block rounded bg-blue-700 px-3 py-2 text-white">{t('network.save', fallback('save', 'Save'))}</button></form></section>
    <section className="mt-6 rounded border p-4"><h2 className="font-semibold">{t('network.map', fallback('map', 'Network map'))}</h2><MapContainer className="mt-3 h-96 rounded" center={[46.8, 8.2]} zoom={8} minZoom={2} maxBounds={[[-85, -180], [85, 180]]} worldCopyJump={false} aria-label={t('network.map', fallback('map', 'Network map'))}><TileLayer attribution="© OpenTopoMap contributors" url="https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png" /><FitBounds points={[...known, ...parsed.flatMap(item => item.receivers)]} />{parsed.flatMap((item, index) => item.receivers.map((receiver, ri) => <CircleMarker key={`receiver-${index}-${ri}`} center={[receiver.lat, receiver.lon]} radius={4} pathOptions={{ color: "#059669" }}><Popup>{receiver.id}</Popup></CircleMarker>))}{known.map((point, index) => <CircleMarker key={`${point.label}-${index}`} center={[point.lat, point.lon]} radius={index === 0 && location ? 8 : 5} pathOptions={{ color: index === 0 && location ? '#dc2626' : '#334155' }}><Popup>{point.label}</Popup></CircleMarker>)}{parsed.flatMap((item, itemIndex) => item.device ? item.receivers.map((receiver, receiverIndex) => <Polyline key={`link-${itemIndex}-${receiverIndex}`} positions={[[item.device!.lat, item.device!.lon], [receiver.lat, receiver.lon]]} pathOptions={{ color: '#334155', dashArray: '4 4' }} />) : [])}</MapContainer>{known.length === 0 && <p className="mt-2 text-sm">{t('network.noKnownLocations', fallback('noKnownLocations', 'No known positions'))}</p>}<p className="mt-2 text-sm">{t('network.mapEvidence', fallback('mapEvidence', 'Only recorded positions are shown; coverage is not inferred.'))}</p></section>
    <section className="mt-6 rounded border p-4"><h2 className="font-semibold">{t('network.observations', fallback('observations', 'Observations'))}</h2><p className="mt-2 text-sm">{t('network.observationCount', { count: observations.length, defaultValue: '{{count}} observations' })}</p>{observations.length === 0 && <p className="mt-2 text-sm">{t('network.noObservations', fallback('noObservations', 'No observations'))}</p>}{observations.map(o => <div key={String(o.id ?? o.recorded_at)} className="border-t py-2 text-sm">{o.deveui} · {o.recorded_at} · {observationRssi(o) ?? t('network.unknown', fallback('unknown', 'Unknown'))}</div>)}{nextOffset !== null && <button type="button" onClick={loadMore} disabled={loadingMore} className="mt-3 rounded border px-3 py-2">{loadingMore ? t('network.loadingMore', fallback('loadingMore', 'Loading…')) : t('network.loadMore', fallback('loadMore', 'Load more'))}</button>}<h3 className="mt-4 font-semibold">{t('network.unknownDevices', fallback('unknownDevices', 'Unknown positions'))}</h3>{devices.filter(d => !known.some(point => point.label === d.deveui)).map(d => <div key={d.deveui} className="text-sm">{d.name} · {t('network.unknown', fallback('unknown', 'Unknown'))}</div>)}</section>
  </main>;
}
